from sentence_transformers import SentenceTransformer
from config import DEVICE, SENTECE_TRANSFORM_MODEL_STR, VECTOR_BD_API_KEY, VECTOR_BD_URL


QDRANT_URL: str = VECTOR_BD_URL
QDRANT_KEY: str = VECTOR_BD_API_KEY

# Трансформеры текста
SENTECE_TRANSFORM_MODEL = SentenceTransformer(SENTECE_TRANSFORM_MODEL_STR)
SENTECE_TRANSFORM_MODEL = SENTECE_TRANSFORM_MODEL.to(DEVICE)